# tools/updateTomSelect.R
#
# Run from the repo root to update the bundled tom-select library.
# Usage: Rscript tools/updateTomSelect.R
#
# Prerequisites: bun, Rscript with jsonlite, sass, and bslib packages installed

# Run an external command and abort if it exits non-zero, mirroring the
# error-handling pattern used by the other tools/update*.R scripts.
run <- function(cmd, args) {
  out <- system2(cmd, args, stdout = TRUE, stderr = TRUE)
  status <- attr(out, "status")
  if (!is.null(status) && status != 0) {
    stop(sprintf("`%s %s` failed (exit %d):\n%s",
                 cmd, paste(args, collapse = " "), status,
                 paste(out, collapse = "\n")))
  }
  invisible(out)
}

message("Installing tom-select via bun...")
run("bun", "install")

# Read installed version
pkg_json <- jsonlite::fromJSON("node_modules/tom-select/package.json")
version  <- pkg_json$version
message("tom-select version: ", version)

# Copy the complete build (includes all plugins)
dest_dir <- "inst/www/shared/selectize/js"
dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)

src  <- "node_modules/tom-select/dist/js/tom-select.complete.js"
dest <- file.path(dest_dir, "tom-select.complete.js")
file.copy(src, dest, overwrite = TRUE)
message("Copied: ", dest)

# Write version file
writeLines(
  c(
    "# Generated by tools/updateTomSelect.R; do not edit by hand",
    paste0('version_selectize <- "', version, '"')
  ),
  "R/version_selectize.R"
)
message("Updated R/version_selectize.R")

# Minify via esbuild. The build scripts in package.json are invoked through
# npm (matching how the rest of the frontend is built); only dependency
# installation uses bun, which writes bun.lock.
message("Minifying JS...")
run("npm", "run bundle_external_libs")

# Regenerate pre-compiled Bootstrap 3 CSS fallback
message("Regenerating css/selectize.bootstrap3.css...")
bs3_path <- system.file("lib/bs3/assets/stylesheets/bootstrap", package = "bslib")
css <- sass::sass(
  input = list(
    sass::sass_file(file.path(bs3_path, "_variables.scss")),
    sass::sass_file(file.path(bs3_path, "_mixins.scss")),
    sass::sass_file("inst/www/shared/selectize/scss/selectize.bootstrap3.scss")
  ),
  options = sass::sass_options(output_style = "compressed")
)
writeLines(css, "inst/www/shared/selectize/css/selectize.bootstrap3.css")
message("Updated css/selectize.bootstrap3.css (", nchar(css), " chars)")

message("\nDone. Commit the following files:")
message("  inst/www/shared/selectize/js/tom-select.complete.js")
message("  inst/www/shared/selectize/js/tom-select.complete.min.js")
message("  inst/www/shared/selectize/css/selectize.bootstrap3.css")
message("  R/version_selectize.R")
message("  bun.lock")
