# tools/updateTomSelect.R
#
# Run from the repo root to update the bundled tom-select library.
# Usage: Rscript tools/updateTomSelect.R
#
# Prerequisites: npm, Rscript with jsonlite, sass, and bslib packages installed

# Run an external command and abort if it exits non-zero, mirroring the
# error-handling pattern used by the other tools/update*.R scripts.
run <- function(cmd, args) {
  out <- system2(cmd, args, stdout = TRUE, stderr = TRUE)
  status <- attr(out, "status")
  if (!is.null(status) && status != 0) {
    stop(sprintf("`%s %s` failed (exit %d):\n%s",
                 cmd, paste(args, collapse = " "), status,
                 paste(out, collapse = "\n")))
  }
  invisible(out)
}

message("Installing tom-select via npm...")
run("npm", "install")

# Read installed version
pkg_json <- jsonlite::fromJSON("node_modules/tom-select/package.json")
version  <- pkg_json$version
message("tom-select version: ", version)

# Copy the complete build (includes all plugins)
dest_dir <- "inst/www/shared/selectize/js"
dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)

src  <- "node_modules/tom-select/dist/js/tom-select.complete.js"
dest <- file.path(dest_dir, "tom-select.complete.js")
file.copy(src, dest, overwrite = TRUE)
message("Copied: ", dest)

# Write version file
writeLines(
  c(
    "# Generated by tools/updateTomSelect.R; do not edit by hand",
    paste0('version_selectize <- "', version, '"')
  ),
  "R/version_selectize.R"
)
message("Updated R/version_selectize.R")

# Minify via esbuild. Both dependency installation and the build scripts in
# package.json go through npm, matching how the rest of the frontend is built.
message("Minifying JS...")
run("npm", "run bundle_external_libs")

# Regenerate the pre-compiled Bootstrap 3 CSS fallback. This file is served
# *raw* to apps that have no bslib theme (selectizeStaticDependency() in
# R/input-select.R), so it must be valid, fully-compiled CSS.
#
# Compile selectize.bootstrap3.scss against bslib's full Bootstrap 3 bundle via
# sass::sass_partial() -- the same machinery the themed path uses at runtime --
# so Bootstrap Sass functions (e.g. color-contrast()) are in scope and resolve.
# A bare sass::sass() of the scss with only _variables/_mixins prepended leaves
# those functions undefined; LibSass then passes them through as literal text,
# producing CSS the browser silently drops.
message("Regenerating css/selectize.bootstrap3.css...")
css_header <- paste0(
  "/*! tom-select.js (https://tom-select.js.org), derived from selectize.js. ",
  "Apache-2.0 License. Bundled with Shiny; do not edit by hand -- regenerate ",
  "via tools/updateTomSelect.R. */\n"
)
css <- sass::sass_partial(
  rules = sass::sass_file("inst/www/shared/selectize/scss/selectize.bootstrap3.scss"),
  bundle = bslib::bs_theme(version = 3),
  options = sass::sass_options(output_style = "compressed"),
  cache = FALSE
)
# Guard: the fallback is consumed raw, so it must never contain uncompiled Sass.
# Match only the uppercase RGB()/RGBA() (LibSass passthrough); compiled output
# legitimately contains lowercase rgba().
if (grepl("@use|@import|\\bmath\\.|color-contrast\\(|\\bRGBA?\\(", css)) {
  stop("selectize.bootstrap3.css still contains uncompiled Sass tokens; ",
       "check the .scss sources for Dart-Sass-only constructs.")
}
writeLines(paste0(css_header, css), "inst/www/shared/selectize/css/selectize.bootstrap3.css")
message("Updated css/selectize.bootstrap3.css (", nchar(css), " chars)")

message("\nDone. Commit the following files:")
message("  inst/www/shared/selectize/js/tom-select.complete.js")
message("  inst/www/shared/selectize/js/tom-select.complete.min.js")
message("  inst/www/shared/selectize/css/selectize.bootstrap3.css")
message("  R/version_selectize.R")
message("  package-lock.json")
